#!/bin/bash -e

#SBATCH --account nesi02659             #Project_Code/Account_Code for tracking
#SBATCH --job-name MyAnalysis           #An indentifier for the user
#SBATCH --time 00:06:00                 #Walltime/Runtime assigned by the user : dd-hh:mm:ss
#SBATCH --ntasks 1                      #how many instances of your command are executed
#SBTACH --cpus-per-task 1               #Number of CPUS requested per task
#SBTACH --mem 1G                        #Amount of memory (TOTAL)
#SBATCH --output=myanalysis-%j.out           #An output file generated by SLURM
#SBATCH --export NONE                   #Required header to allow submitting from a JupyterLab-based terminal

export SLURM_EXPORT_ENV=ALL             #Required command to allow for submitting from a JupyterLab-based terminal

module purge
module load R/4.0.1-gimkl-2020a

Rscript analysis.R